### ISSUE TITLE
The bot should more Pokemon

### ISSUE THREAD

**Issue by swt2public** [rheaSPK/py-twitter-bot#5]
Given a tweet "Which Pokemon is #2",
Then the bot's answer should contain "Ivysaur".

* It's enough if the bot knows Pokemon #1 to #9
        

>Expected response to contain "Ivysaur",  
but got "Hi @TestUser! It is 19:08:37 on a Tuesday (30-05-2017).".

**Comment by rheaSPK** [comment]
Fixed
